/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@interface SBApplicationController
+ (id)sharedInstance;
- (SBApplication*)applicationWithDisplayIdentifier:(NSString*)identifier;
@end

@interface SBUIController
+ (id)sharedInstance;
- (void)activateApplicationFromSwitcher:(SBApplication*)app;
@end

@interface SBIconModel
+ (id)sharedInstance;
- (id)leafIconForIdentifier:(id)fp8;
@end

@interface SBIcon
- (void)launchFromViewSwitcher;

@end

@interface SBAwayController
- (void)unlockWithSound:(BOOL)fp8;
@end

@interface ALApplicationList
+ (id)sharedApplicationList;
- (UIImage *)iconOfSize:(int)iconSize forDisplayIdentifier:(NSString *)displayIdentifier;
@end